export { default as Home} from './Home'
export { default as ProductDetails} from  './ProductDetails'
export {default as LogIn} from './LogIn'
export {default as Purchases} from './Purchases'
export {default as ProtectedRoutes} from './ProtectedRoutes'
